### ISSUE TITLE
Move this plugin into the dprint organization

### ISSUE THREAD

**Issue by thomaseizinger** [thomaseizinger/dprint-plugin-cargo-toml#1]
cc @dsherret

At the moment things are pretty bare-bones in here (no readme, docs etc).

What would it take to make this an official dprint plugin? Are you even interested in that or is your vision more along the lines of what is currently happening (i.e. community members host their own plugin releases)?

**Comment by dsherret** [comment]
@thomaseizinger I'd like to have a toml plugin in addition to this plugin before putting it on the site and perhaps we could merge the work you've done here into that. I looked into it more today and it looks like what you're using in here (toml-parse) would be good to use. I don't think it will take too much time as toml is very simple. Maybe I will start on it tomorrow.

**Comment by thomaseizinger** [comment]
@dsherret  `toml-parse` is sort of unmaintained (see the linked PR in the readme of my plugin).

I think I general toml plugin makes sense, although some of the rules implemented here are specific to `Cargo.toml`, f.e. the order of things within `[package]` is not alphabetical.

Do you envision a toml plugin to have support for these special files or would you drop/generalize the formatting rules?

**Comment by dsherret** [comment]
@thomaseizinger if we want that route, I was thinking that there could be a configuration option to turn it off, but by default if the file name was `Cargo.toml` then it would format it according to those rules you created.

That's disappointing about `toml-parse`... yeah I ran into a bug on the first thing I tried from the spec so that wasn't encouraging, but it was a small bug. `taplo` looks pretty good though. It already has a formatter, but toml is not too complex and I could build a formatter quickly so I'd rather build one as that will give us the ability to swap out the parser or whatever in the future and have more control.

**Comment by thomaseizinger** [comment]
I am happy for you to move forward as you best see fit. The hardest thing I found was preserving comments when doing the re-ordering. If you end up building your own parser / formatter, that is something to look out for :)

**Comment by dsherret** [comment]
@thomaseizinger thanks for sponsoring dprint! Really appreciate it.

Just an update that I worked on this a bit last weekend and this weekend and I'm probably about 20% done. It's going pretty smoothly.

Nice thing about toml is that there can only be comments at the end of a line, so that makes the formatting code a lot easier. I know the challenge because it was done in dprint-plugin-typescript https://dprint.dev/playground/#code/PQKgBAwmLGCWBbADgewE4BcwG8C+YAzNFBMAIgDpgIyxhYIBYAKFDACFpZFVMd8iJclXa16HFmwCCXeMnRY8hYqUrApY2FKA/language/typescript

**Comment by dsherret** [comment]
@thomaseizinger it ended up being faster than I expected to get this is basically done https://github.com/dprint/dprint-plugin-toml (still needs to be tested out on more code though)

I think we could integrate this plugin into there by checking if the file name is `Cargo.toml` and if so, running the `SyntaxNode` through a pre-processing step that does what's done in this repo before passing it to `parser::parse_items` in dprint-plugin-toml (see [format_text.rs](https://github.com/dprint/dprint-plugin-toml/blob/main/src/format_text.rs)). Does that make sense? Would you be up for integrating your changes?

**Comment by thomaseizinger** [comment]
> @thomaseizinger it ended up being faster than I expected to get this is basically done https://github.com/dprint/dprint-plugin-toml (still needs to be tested out on more code though)
> 
> I think we could integrate this plugin into there by checking if the file name is `Cargo.toml` and if so, running the `SyntaxNode` through a pre-processing step that does what's done in this repo before passing it to `parser::parse_items` in dprint-plugin-toml (see [format_text.rs](https://github.com/dprint/dprint-plugin-toml/blob/main/src/format_text.rs)). Does that make sense? Would you be up for integrating your changes?

I'll give it a shot yes!

**Comment by thomaseizinger** [comment]
Release 0.3.2 of https://github.com/dprint/dprint-plugin-toml fixes this!
